Add ODIN
kardiachain/token-assets pull request #5
Opened 2021-11-04 13:00 UTC by hooginn

2021-11-05 04:35 UTC, phongnhat19 requested changes
Please provide tx hash for payment

2021-11-07 22:34 UTC, hooginn commented
> Please provide tx hash for payment

Here is the transaction hash: `0x0e7ced1f50efd8e3413ca9b70b968862d21e4321cc5ffabb357ddc4aa6352c97`

2021-11-08 04:55 UTC, phongnhat19 approved these changes

2021-11-08 06:26 UTC, phongnhat19 commented
LGTM

2021-11-08 06:27 UTC, merged